### PR TITLE
adding ability to parse default bash variables such as ${foo:-bar} 

### PR DESCRIPTION
**Pull request by vito-c**
title is pretty straight forward. This let's you add default values to your docker-compose file.
```
web:
# unbracketed name
image: ${IMAGE:-busybox}
```
parsers to
```
web:
# unbracketed name
image: busybox
```
```
web:
# unbracketed name
image: ${IMAGE-busybox}
```
parsers to
```
web:
# unbracketed name
image: busybox
```

### CODE REVIEW

**Comment by patrick-bohan** [comment]
Does this support the `${VARIABLE-default}` format (without the ":") as well? https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by vito-c** [comment]
@patrick-bohan no but I could add support for that.

**Comment by vito-c** [comment]
added support for `-` and some more testing.

**Comment by vito-c** [comment]
@vdemeester What is the timeline like to get merges?

**Pull request merged**
