### PR TITLE
Bump to docker 1.10-dev and dependencies

### LINKED ISSUE #32: libcompose should be go gettable/buildable/testable
As documented, the build and test process are currently driven by a `Makefile` performing actions in a container.

Since this is a library, it should be `go gettable/buildable/testable` out of the box without having to run a non-standard process.

There are apparently dependencies against non-pkg parts of docker which make it tricky to do so.

### PR DESCRIPTION
**Pull request by vdemeester**
This is more a *try* (or a *"it would look like this"* kinda thing) than a real thing because this feels almost too early to bump a docker version but as we still don't have versions, so it feel safer (will probably just have to bump it on the way later too).

Anyway, what this does is bumping to current master (my dream is to bump it on a tag but… it's not gonna happen until `1.10`) to remove the `autogen/dockerversion` thingy and make it *go gettable/buildable/testable*, and thus would fix #32.

- go gettable/…
- No more use of `go generate`,
- Keep the source up-to-date and update a little tiny bit the code base to compile with it :wink:.

@ibuildthecloud @docker/libcompose-maintainers WDYT ?

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I like the idea, and I'm fine with pulling this in before 1.10 is released.  It's almost safer to bump now as it's closer to 1.9 as it is right now.

**Comment by vdemeester** [comment]
@ibuildthecloud cool :smile_cat: Then I have to see why the integration tests are failing and fix it :stuck_out_tongue_closed_eyes:.

**Comment by vdemeester** [comment]
Updated with some fixes. I splited the commit into two, one for the vendoring, the other one for the fix.
Build should be green :wink:.

**Comment by gondor** [comment]
Great idea @vdemeester ! Very happy with this :) as it will be go gettable it appears

**Comment by vdemeester** [comment]
ping @ibuildthecloud @dnephin

**Comment by dnephin** [comment]
Changes in the second commit seem fine. 
I think it's ok to use a pre-release version of Docker.
Can't really review the `vendor/` change

LGTM

**Comment by imikushin** [comment]
@vdemeester Does this work with docker-1.9.1? If it does, maybe vendor it?

**Comment by vdemeester** [comment]
@imikushin I could update the "hash" but the `dockerversion` thingy was not cherry-picked on `1.9.1` so the whole point of this PR wouldn't be met with `1.9.1` :stuck_out_tongue_closed_eyes:

**Comment by imikushin** [comment]
@vdemeester to get rid of `go generate`? okay :+1:

**Comment by gondor** [comment]
@vdemeester Do you have any timeline on when this will be merged?

**Comment by ibuildthecloud** [comment]
LGTM

**Pull request merged**
