### PR TITLE
Unmarshal empty string slices as nil

### PR DESCRIPTION
**Pull request by imikushin**
Unmarshal empty string slices as nil. 

The problem is: if we have an empty slice as a command or entrypoint (e.g. in marshaled service config) 
docker API yells we're passing an empty command or entrypoint. But it doesn't mind having nils. 

Also, bump test dependencies for nicer unit test errors. Bump Go as well.

Signed-off-by: Ivan Mikushin <i.mikushin@gmail.com>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by aanand** [comment]
Thanks. Could you separate the version bumps out into another commit?

**Comment by vdemeester** [comment]
LGTM 🐲 but I do agree with @aanand

**Comment by imikushin** [comment]
Here you are: two separate nice little commits :)

**Comment by vdemeester** [comment]
:heart_eyes_cat:

**Pull request merged**
