### PR TITLE
Switch client to engine-api

### PR DESCRIPTION
**Pull request by vdemeester**
Now that the engine API has been split out in [docker/engine-api](https://github.com/docker/engine-api), it make sense that libcompose uses it, as it is the official API lib, maintained by docker maintainer and shared with other project (the engine, swarm, …).

As with vendoring PRs, it's a little *heavy*, the commit to look at is https://github.com/docker/libcompose/commit/bb00c3edc58fb64dd41b1406addcccf5e128d0fb.

<del>**Note: This is based on #144 so it would need to be merged before that one** (hence the WIP).</del>

- [x] There is still some `FIXMEs`
- [x] The default `API_VERSION` is now `1.20`, which is for docker `v1.8.x`, and as it is, I did not test against lower version. I'll have to make some tests, because I would like libcompose to support at least `1.8` and `1.9`.

**Note: It makes the default assumption that the API behind it is `v1.20`.** Using the cli, you can specify it using the `DOCKER_API_VERSION` and I will make a follow-up PR to allow to add a flag on it. Using the API, you can pass `APIVersion` to the `ClientOpts` when creating the client.

/cc @ibuildthecloud @dnephin @imikushin

### CODE REVIEW

**Comment by runcom** [comment]
this is hugeeeee

**Comment by vdemeester** [comment]
ping @runcom and @calavera to get more eyes on this :stuck_out_tongue:

**Comment by calavera** [comment]
LGTM

**Comment by imikushin** [comment]
Not looking very good :mask: here:
```
➜  libcompose git:(pr146) ./libcompose --verbose -p test-project1 -f - up -d < tmp/compose.yml
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
0EBU[0000] Trusting certs with subjects: [01
 U
ivan] 
DEBU[0000] Opening compose files: -                     
DEBU[0000] [0/1] [hello]: Adding                        
INFO[0000] Project [test-project1]: Starting project    
DEBU[0000] Launching action for hello                   
INFO[0000] [0/1] [hello]: Starting                      
ERRO[0000] Failed Starting hello : Error response from daemon: json: cannot unmarshal object into Go value of type []string 
ERRO[0000] Failed to start: hello : Error response from daemon: json: cannot unmarshal object into Go value of type []string 
FATA[0000] Error response from daemon: json: cannot unmarshal object into Go value of type []string 
```

compose.yml:
```yml
hello:
  image: busybox
  stdin_open: true
  tty: true
```

Here's the output from master:
```
➜  libcompose git:(master) ./libcompose --verbose -p test-project1 -f - up -d < tmp/compose.yml
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
DEBU[0000] Opening compose files: -                     
DEBU[0000] [0/1] [hello]: Adding                        
INFO[0000] Project [test-project1]: Starting project    
DEBU[0000] Launching action for hello                   
INFO[0000] [0/1] [hello]: Starting                      
DEBU[0000] Found 0 existing containers for service hello 
DEBU[0001] Creating container test-project1_hello_1 &docker.CreateContainerOptions{Name:"test-project1_hello_1", Config:(*docker.Config)(0xc820184540), HostConfig:(*docker.HostConfig)(0xc8202baa00)} 
DEBU[0001] Created container 36447c3049132d29e508b683788a8c04334793335d2ab8380621956ef0705070: [/test-project1_hello_1] 
DEBU[0001] [0/1] [hello]: Created container name=test-project1_hello_1 
DEBU[0001] Checking existing image name vs id: b175bcb790231169e232739bd2172bded9669c25104a9b723999c5f366ed7543 == b175bcb790231169e232739bd2172bded9669c25104a9b723999c5f366ed7543 
DEBU[0001] Going to decide if recreate is needed         ForceRecreate=false NoRecreate=false outOfSync=false
DEBU[0001] Starting container                            c.name=test-project1_hello_1 container.ID=36447c3049132d29e508b683788a8c04334793335d2ab8380621956ef0705070
DEBU[0001] [0/1] [hello]: Started container name=test-project1_hello_1 
INFO[0001] [1/1] [hello]: Started                       
```

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 3
Images: 964
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 970
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 15.63 GiB
Name: ivan-machine-packet
ID: MUL2:IBSJ:UTMR:O4IL:QXIK:2NFO:5DUW:A76Z:QR3S:NPCR:3YKB:7ZKS
Username: shengliang
Registry: https://index.docker.io/v1/
Labels:
 provider=packet
```

**Comment by vdemeester** [comment]
@imikushin I guessed it would do that.. If you set up the `DOCKER_API_VERSION` to v1.21 it should work. I'll set a default version lower than v1.22 to be more backward compatible 😇

**Comment by imikushin** [comment]
I've tried to compile with `DefaultAPIVersion   = "1.21"` in docker/client.go, but the ~~song~~ error remains the same.

**Comment by vdemeester** [comment]
yeah it won't work that way 'cause it's using th env client. I'll update the PR tomorrow :wink:

**Comment by vdemeester** [comment]
@imikushin Can you try it back now ? It should work in both with `1.9.x` (API `v1.21`) and `1.8` (API `v1.20`) as it's setting default api version to `v1.20` in not specified (either using `libcompose-cli` binary or the API).

**Comment by imikushin** [comment]
It's working now!

**Comment by vdemeester** [comment]
Ok let's merge this, and we'll iterate from that :angel:

**Comment by bfosberry** [comment]
<3 !!

**Pull request merged**
