### PR TITLE
Update example

### LINKED ISSUE #261: not able to run example program main.go
Trying to run https://github.com/docker/libcompose/blob/master/example/main.go and getting error as:

```bash
$ go run main.go 
# command-line-arguments
./main.go:22: not enough arguments in call to project.Up
```
on compose file

```yaml
$ cat docker-compose.yml 
postgresql:
  image: swordphilic/postgresql
  ports:
    - "5432"
  environment:
    DB_NAME: gitlab
    DB_PASS: gitlab
    DB_USER: gitlab

gitlab:
  image: swordphilic/gitlab
  ports:
    - "30000:80"
    - "30001:443"
    - "30002:22"
  links:
    - redis
    - postgresql
  environment:
    DB_TYPE: postgres
    DB_NAME: gitlab
    DB_PASS: gitlab
    DB_USER: gitlab

redis:
  image: swordphilic/redis
  ports:
    - "6379"
```

### PR DESCRIPTION
**Pull request by marclop**
* Update the libcompose example to include the latest changes to the interface.
* fix #261 
* Add `.idea` to `.gitignore`

### CODE REVIEW

**Comment by joshwget** [comment]
#259 will also require a change to the example (at least as the PR is now). We should leave this open until that's merged :smile:

**Comment by marclop** [comment]
that's cool for me!

**Comment by vdemeester** [comment]
Thanks @marclop, I carried your commit in #274 :wink:

**Comment by marclop** [comment]
Thanks @vdemeester, missed a comma in the example, dunno why didn't show in `go vet` when I ran it in the example folder 🙀

**Pull request closed without merging**
