### PR TITLE
don't forget to create the container after pulling its image

### PR DESCRIPTION
**Pull request by imikushin**
don't forget to create the container after pulling its image

### CODE REVIEW

**Comment by vdemeester** [comment]
@imikushin Thanks for contributing. 
Note that I fixed that in #10 (to make the build greens), so this one might be not needed (sorry :sweat_smile: :blush:) if #10 is merged.

**Comment by imikushin** [comment]
@vdemeester That's great! Don't really care which one gets merged :)

**Comment by vdemeester** [comment]
@imikushin #11 is merged, you can close this one :sweat_smile:.

**Comment by ibuildthecloud** [comment]
Closing as this is fixed in #11.  thanks @imikushin

**Pull request closed without merging**
