### PR TITLE
Add @vdemeester as maintainer

### PR DESCRIPTION
**Pull request by ibuildthecloud**
I'd like propse @vdemeester be added as a maintainer to libcompose.  From the very beginning @vdemeester has been very active in libcompose and submitted the majority of the PRs.  @vdemeester is already a maintainer on the Docker Engine and is a trusted and respected member of this community.  It seems only nature to add him as a maintainer.

@aanand @gdevillele @dnephin @gdevillele

### CODE REVIEW

**Comment by thaJeztah** [comment]
not a maintainer here, but LGTM :+1:

**Comment by aanand** [comment]
LGTM

**Comment by vdemeester** [comment]
:heart_eyes_cat:

**Comment by dnephin** [comment]
LGTM

**Comment by vdemeester** [comment]
:tada: :kissing_cat:

**Comment by thaJeztah** [comment]
Congrats Vincent!

**Pull request merged**
