### PR TITLE
Fixes parsing of environment dictionary keys

### PR DESCRIPTION
**Pull request by janeczku**
https://github.com/docker/libcompose/issues/296

Verified that this fixes parsing environment dictionary.

### CODE REVIEW

**Comment by joshwget** [comment]
I think keys with missing values should be converted to just the key name (`VAR`, not `VAR=`). This matches how the feature works when environment variables are specified as an array. Thanks for catching this issue! :smile:

**Comment by janeczku** [comment]
@joshwget Updated the PR to use just the key name without separator (`=`).

**Comment by joshwget** [comment]
Awesome! LGTM.

**Comment by vdemeester** [comment]
I'll check the build locally (we're having some trouble with the CI… it takes time to run and it's failing for some weird reason :sweat: )

**Comment by vdemeester** [comment]
LGTM :wink:

**Pull request merged**
