### PR TITLE
Add jenkins badge (build) and godoc badge

### PR DESCRIPTION
**Pull request by vdemeester**
Add some badges (godoc and the build status 🐢).

/cc @ibuildthecloud :wink: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks @vdemeester, nice!

**Comment by ibuildthecloud** [comment]
@vdemeester why does the badge have swarm in it?

**Comment by vdemeester** [comment]
@ibuildthecloud arg.. a typo.. I'll fix that..

**Comment by thaJeztah** [comment]
> why does the badge have swarm in it?

Oh! No more late night reviewing for me, lol

**Comment by vdemeester** [comment]
@thaJeztah :sweat_smile:

**Comment by gdevillele** [comment]
LGTM 🐹

**Pull request merged**
