### PR TITLE
Add some info to contributing.md

### PR DESCRIPTION
**Pull request by thaJeztah**
Blatantly copied from the Swarm repository, but at least there's some info now in the document that GitHub will link to when opening issues and PR's :smile:

### CODE REVIEW

**Comment by vdemeester** [comment]
:+1: LGTM

**Comment by thaJeztah** [comment]
@ibuildthecloud @aduermael @gdevillele Related to this; I noticed that the older commits are not signed-off; will that be a problem? Is there some way to amend that; IANAL, so I'm not sure if the unsigned commits could become a problem

**Comment by ibuildthecloud** [comment]
@thaJeztah I believe the only unsigned commits are from Docker employees only which legally all there work belongs to Docker, Inc anyhow.  Do you see others?  Too late to change history I feel.

**Comment by thaJeztah** [comment]
@ibuildthecloud yes, I think they're all Docker Employees, and I'm really bad at this stuff; I was just wondering if the missing sign-offs could cause trouble (e.g. Rancher being sued because they included code that wasn't explicitly signed-off). I live in a country that isn't as lawyer-driven as the USA, but I remembered this thread; http://discuss.gohugo.io/t/switching-to-apache-2-license/173

Just wanted to confirm its all covered, now that the list of contributors is still small, and still relatively easy to resolve.

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by gdevillele** [comment]
LGTM

**Pull request merged**
