### PR TITLE
WIP - Adding Failure events to event types and to service wrapper

### PR DESCRIPTION
**Pull request by bfosberry**
This change adds a set of project and service level failure events to the
list of possible events, as well as to the service wrapper function calls.

This allows users to determine whether an action has failed by viewing events.

The only behaviour changed here, other than additional events passing through
the notification system, is that when a project action fails, it will no longer
post the relevant 'done' event.

### CODE REVIEW

**Comment by vdemeester** [comment]
@bfosberry I like the idea ; I wonder if we should refactor the event stuff though — we almost always define 3 type for each events (`ProjectStart` : `…Start`, `…Stop`, `…Failure`). It would also simplify a bit the method signature of `p.perform`. What do you think ?

**Comment by bfosberry** [comment]
We could use more typed events with a start, done, fail field, push the text description in, and strictly type the data. End users could do a type switch

**Comment by vdemeester** [comment]
@bfosberry yeah, this is more or less what I was thinking :stuck_out_tongue_closed_eyes:

**Comment by bfosberry** [comment]
Switching this to WIP, this'll probably affect the stopping container PR also, I'll separate that out

**Comment by vdemeester** [comment]
:+1:

**Comment by bfosberry** [comment]
@vdemeester let me get your thoughts on this approach:

```
// Event holds project-wide event information.
type Event interface {
	ServiceName() string
	String() string
}

type baseEvent struct {
	serviceName string
	eventName   string
}

// ServiceName returns the name of the service for the event
func (e *baseEvent) ServiceName() string {
	return e.serviceName
}

// String returns a string representation of the event
func (e *baseEvent) String() string {
	return e.eventName
}

func newBaseEvent(serviceName, eventName string) *baseEvent {
	return &baseEvent{
		serviceName: serviceName,
		eventName:   eventName,
	}
}

// EventFactory creates a new Event for a specified service
type EventFactory func(serviceName string) Event

// EventWrapper provides a wrapper around EventFactories to allow
// state dependent Event generation
type EventWrapper interface {
	Started(string) Event
	Failed(string) Event
	Done(string) Event
}

type eventWrapper struct {
	startedFactory EventFactory
	failedFactory  EventFactory
	doneFactory    EventFactory
}

// Started creates a new event using the provided EventFactory for
// the 'started' condition
func (wrapper *eventWrapper) Started(serviceName string) Event {
	if wrapper.startedFactory {
		return wrapper.startedFactory(serviceName)
	} else {
		return nil
	}
}

// Failed creates a new event using the provided EventFactory for
// the 'failed' condition
func (wrapper *eventWrapper) Failed(serviceName string) Event {
	if wrapper.failedFactory {
		return wrapper.failedFactory(serviceName)
	} else {
		return nil
	}
}

// Done creates a new event using the provided EventFactory for
// the 'done' condition
func (wrapper *eventWrapper) Done(serviceName string) Event {
	if wrapper.doneFactory {
		return wrapper.doneFactory(serviceName)
	} else {
		return nil
	}
}

// NewEventWrapper builds a wrapper around the provided EventFactories
func NewEventWrapper(started EventFactory, done EventFactory, failed EventFactory) EventWrapper {
	return &eventWrapper{
		startedFactory: started,
		failedFactory:  failed,
		doneFactory:    done,
	}
}

// *** Events ***

// EventContainerStarted indicates a container has started
type EventContainerStarted struct {
	*baseEvent
	ContainerName string
}

// NewEventContainerStarted returns a ContainerStarted Event
func NewEventContainerStarted(serviceName, containerName string) Event {
	return &EventContainerStarted{
		baseEvent:     newBaseEvent(serviceName, "Started container"),
		ContainerName: containerName,
	}
}

// EventContainerCreated indicates a container has started
type EventContainerCreated struct {
	*baseEvent
	ContainerName string
}

// NewEventContainerCreated returns a ContainerCreated Event
func NewEventContainerCreated(serviceName, containerName string) Event {
	return &EventContainerCreated{
		baseEvent:     newBaseEvent(serviceName, "Created container"),
		ContainerName: containerName,
	}
}

// EventServiceAdd indicates a container has started
type EventServiceAdd struct {
	*baseEvent
}

// NewEventServiceAdd returns a ServiceAdd Event
func NewEventServiceAdd(serviceName) Event {
	return &EventServiceAdd{
		baseEvent:     newBaseEvent(serviceName, "Adding"),
		ContainerName: containerName,
	}
}

/*
// NewEventContainerCreatedFactory returns an EventFactory
// for an EventContainerCreated event
func NewEventContainerCreatedFactory(containerName string) EventFactory {
	return func(serviceName string) NewEvent {
		return NewEventContainerCreated(serviceName, containerName)
	}
}
*/
```

We'd have heavily typed event structs, and pass those into the channels directly. The Notify method signature would reduce to just taking an event. The factories and wrappers are for cases where we conditionally need events for Done/Started/Failed or potentially other situations, and separate the common args of serviceName, from the event specific args like container name and id.

Usage of the wrapper would look something like this:

```
func (p *Project) perform(eventWrapper EventWrapper, services []string, action wrapperAction, cycleAction serviceAction) error {
	p.Notify(eventWrapper.Started())

	err := p.forEach(services, action, cycleAction)

	if err != nil {
		p.Notify(eventWrapper.Failed())
	} else {
		p.Notify(eventWrapper.Done())
	}
	return err
}
```

On the receiving end a user could use standard go type switching to access the events:

```
switch event := event.(type) {
case *EventContainerCreated:
     fmt.Printf("%s - %s\n", event.String(), event.ContainerName)
}
```

Before I copy/paste this 50 times I wanted to run the approach by you.

**Comment by bfosberry** [comment]
ping @vdemeester  thoughts on this ^ approach?

**Comment by vdemeester** [comment]
@bfosberry sorry I'm on vacation this week (so I'm not really active). I'll get back at you next week :sweat_smile:

**Comment by bfosberry** [comment]
Gotcha, thanks for the response, have fun! I'll work on something else for the time being

**Comment by bfosberry** [comment]
ping @vdemeester what do you think of this approach?

**Comment by bfosberry** [comment]
Can I get some feedback on this so I can continue? I may have to start merging on a fork to unblock my team

**Comment by vdemeester** [comment]
@bfosberry I'll take a look this evening, I promise :wink:. 
Got a little bit carried away (with work and healthy related stuff..)

**Comment by bfosberry** [comment]
thanks! We are really eager to start implementing this lib our side, it will fix a lot of issues for us.

**Comment by vdemeester** [comment]
Overall I think I like it but it feels a little bit complex and redudant to define but easy to use :heart_eyes_cat:, mainly the factories.

/cc @dnephin @ibuildthecloud

**Comment by vdemeester** [comment]
@bfosberry what do you prefer we do here ? merging as is and do the refactoring in a separate PR, or making the refactoring in this PR ? :wink:

**Comment by bfosberry** [comment]
We should not merge as is, because what was implemented is not suitable IMHO. I can implement what I commented with fairly quickly, what do you think?

**Comment by vdemeester** [comment]
@bfosberry let's go for it :wink:

**Comment by kunalkushwaha** [comment]
Hi, Is there any update on this?

I am trying to implement https://github.com/docker/libcompose/issues/207 and it seems event for failures are required to complete the state-machine

**Comment by vdemeester** [comment]
@kunalkushwaha implementi'g #207 needs some event 'watching' but not necessarly this refactoring. I'm working on fixing the log command (and thus a small part of #207) thid week, it should help you / give you inspiration for #207.

**Comment by kunalkushwaha** [comment]
@vdemeester while working on ``--abort-on-container-exit``, I felt need of error events, Now I realised may be container events can also be used for same.
Though would like to see your implementation for reference. It will help :)

**Comment by bfosberry** [comment]
Hey @kunalkushwaha , picking this up again soon

**Comment by bfosberry** [comment]
Replacing this PR with https://github.com/docker/libcompose/pull/347

**Pull request closed without merging**
