### PR TITLE
support command ps -q

### PR DESCRIPTION
**Pull request by bohai**
Replace #61 because of my miss.
Signed-off-by: bohai <bohai@huawei.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
@bohai you have a test failure (`TestService`).

**Comment by bohai** [comment]
ping @vdemeester
I have fix the test failture.

**Comment by vdemeester** [comment]
@bohai cool :wink: Could you add an integration test on that ?

**Comment by vdemeester** [comment]
LGTM 🐼

**Comment by vdemeester** [comment]
@bohai Carried :wink:

**Pull request closed without merging**
