### PR TITLE
Fix validate-dco and temporarly remove validate-git-marks from default bundles

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Isn't this still useful if you run make locally?

**Comment by vdemeester** [comment]
@ibuildthecloud I'm trying things out :sweat_smile:. But locally you would do `make validate` (or `make validate-dco`) and this would run `validate-dco` no problem. This is purely for the CI.

**Comment by ibuildthecloud** [comment]
I merged https://github.com/docker/libcompose/pull/20, don't know if that impacts you much.

**Comment by vdemeester** [comment]
@ibuildthecloud no no that won't :stuck_out_tongue_closed_eyes:. I'm gonna push in a few minutes something that should fix the build (on janky) :wink:.

Then we'll see how we handle `validate-dco` as it checks older commits and some are not signed-off so it fails :sweat:.

**Comment by vdemeester** [comment]
@ibuildthecloud Fixed the problem without removing `validate-dco` which is very good. The problem was in `script/.validate`. 

There is a weird stuff with `validate-git-marks` though. I'll try one more thing to see if it builds. If not, I think we should temporarly remove it from the default bundle (so the build is green), and I'll fix that tomorrow morning (Europe/Paris timezone). WDYT ?

**Comment by ibuildthecloud** [comment]
I'm fine with disabling git marks temporarily.  The script is more useful when you have lots of docs.  For go files they obviously won't compile so you don't need the validation.  Being that we have no docs :) we are safe atm.

**Pull request merged**
