### PR TITLE
Fix TLS support

### PR DESCRIPTION
**Pull request by imikushin**
#92, only rebased and golint shut up. 

Thanks to @dhiltgen!

### CODE REVIEW

**Comment by imikushin** [comment]
@ibuildthecloud @vdemeester Please take a look

**Comment by dhiltgen** [comment]
:+1:

**Comment by vdemeester** [comment]
Gonna try this out this evening but the code looks good to me :wink:

**Comment by vdemeester** [comment]
Yeah it fixes TLS, thanks @imikushin @dhiltgen 
LGTM

**Pull request merged**
