### PR TITLE
migrate to fsouza/go-dockerclient

### PR DESCRIPTION
**Pull request by imikushin**
Implementing #71.

This is a work in progress because integration tests do not pass yet.

### CODE REVIEW

**Comment by imikushin** [comment]
@vdemeester Jenkins complains about the library coding style. Looks like that dockerclient is below the our coding standards, as well as our own integration tests :stuck_out_tongue_winking_eye:

**Comment by ibuildthecloud** [comment]
not sure why its checking stuff in `Godeps`, that's odd

**Comment by vdemeester** [comment]
hum.. there is some weird things going on with `validate-golint`.. :sweat: Looking into it :wink:

**Comment by imikushin** [comment]
I've just rebased on top the latest master

**Comment by imikushin** [comment]
@ibuildthecloud @vdemeester I rebased again. Any human feedback on the code while robots are trying to build this? (Integration tests should pass: I've checked)

**Comment by ibuildthecloud** [comment]
@imikushin I added comments on the commit https://github.com/imikushin/libcompose/commit/06d6abf6816f600116b7791a8888c20973816154

**Comment by imikushin** [comment]
Although I believe I've addressed all comments, I don't mind receiving more, especially, LGTM :wink:

**Comment by imikushin** [comment]
Rebased and squashed, updated to using HostConfig.CPUSetCPUs instead of HostConfig.CPUSet (as per docker API 1.20). Updated create_test.go accordingly

**Comment by vdemeester** [comment]
Couple of nits, otherwise I think it's good to go.

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by vdemeester** [comment]
All right, LGTM for me too 🐸

**Comment by thaJeztah** [comment]
thank you @imikushin, great work! :tada:

**Comment by flower-pot** [comment]
This is amazing stuff definitely going to be able to finish #45 nicely now!

**Comment by imikushin** [comment]
Really glad we did it :smiley_cat:

**Pull request merged**
