### PR TITLE
Modify help info format same as docker

### PR DESCRIPTION
**Pull request by bohai**
### Before:
```
[root@localhost integration]# libcompose --help
NAME:
   libcompose-cli - Command line interface for libcompose.

USAGE:
   libcompose-cli [global options] command [command options] [arguments...]

VERSION:
   0.0.0-dev (HEAD)

AUTHOR:
  Docker Compose Contributors - <https://github.com/docker/libcompose>

COMMANDS:
   build	Build or rebuild services.
   create	Create all services but do not start
   up		Bring all services up
   start	Start services
   logs		Get service logs
   restart	Restart services
   stop, down	Stop services
   scale	Scale services
   rm		Delete services
   pull		Pulls images for services
   kill		Force stop service containers
   port		Print the public port for a port binding
   ps		List containers
   help, h	Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --verbose, --debug			
   --file, -f "docker-compose.yml"	Specify an alternate compose file (default: docker-compose.yml) [$COMPOSE_FILE]
   --project-name, -p 			Specify an alternate project name (default: directory name)
   --tls				Use TLS; implied by --tlsverify
   --tlsverify				Use TLS and verify the remote [$DOCKER_TLS_VERIFY]
   --tlscacert 				Trust certs signed only by this CA
   --tlscert 				Path to TLS certificate file
   --tlskey 				Path to TLS key file
   --configdir 				Path to docker config dir, default ${HOME}/.docker
   --help, -h				show help
   --version, -v			print the version
[root@localhost libcompose]# libcompose help rm
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
NAME:
   rm - Delete services

USAGE:
   command rm [command options] [arguments...]

OPTIONS:
   --force, -f	Allow deletion of all services
```
## After:
```
[root@localhost command]# libcompose --help
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
Usage: libcompose-cli [OPTIONS] COMMAND [arg...]

Command line interface for libcompose.

Version: 0.0.0-dev (HEAD)

Author:
  Docker Compose Contributors - <https://github.com/docker/libcompose>

Options:
  --verbose, --debug			
  --file, -f "docker-compose.yml"	Specify an alternate compose file (default: docker-compose.yml) [$COMPOSE_FILE]
  --project-name, -p 			Specify an alternate project name (default: directory name)
  --tls					Use TLS; implied by --tlsverify
  --tlsverify				Use TLS and verify the remote [$DOCKER_TLS_VERIFY]
  --tlscacert 				Trust certs signed only by this CA
  --tlscert 				Path to TLS certificate file
  --tlskey 				Path to TLS key file
  --configdir 				Path to docker config dir, default ${HOME}/.docker
  --help, -h				show help
  --version, -v				print the version
  
Commands:
  build		Build or rebuild services.
  create	Create all services but do not start
  up		Bring all services up
  start		Start services
  logs		Get service logs
  restart	Restart services
  stop, down	Stop services
  scale		Scale services
  rm		Delete services
  pull		Pulls images for services
  kill		Force stop service containers
  port		Print the public port for a port binding
  ps		List containers
  help, h	Shows a list of commands or help for one command
  
Run 'libcompose-cli COMMAND --help' for more information on a command.

[root@localhost command]# libcompose help rm
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
Usage: main rm [OPTIONS]

Delete services

Options:
   --force, -f	Allow deletion of all services
```
Signed-off-by: Bo Hai <bohai@huawei.com>

### CODE REVIEW

**Comment by bohai** [comment]
ping @aanand @aduermael @ibuildthecloud @gdevillele

**Comment by ibuildthecloud** [comment]
@bohai It's not really obvious to me what changed.  I don't really care either way, so I'm fine with this change if it makes it more consistent with other projects.  Just curious what the motivation is and why this format is better.

**Comment by bohai** [comment]
@ibuildthecloud  
Thank you for your reply.

The aim is to keep the libcompose's command style is similar with other projects in the Docker community.
Then the user will have consistent user experience when use the docker tools.

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by vdemeester** [comment]
ping @aduermael @gdevillele

**Comment by vdemeester** [comment]
LGTM

**Comment by thaJeztah** [comment]
hm... wanted to say "press the button", but looks like @vdemeester doesn't have write access yet to this repo :smile:

**Comment by vdemeester** [comment]
@thaJeztah well... yeah :sweat_smile: :stuck_out_tongue_closed_eyes:

**Pull request merged**
