### PR TITLE
Add Installation step for Libcompose Developers

### PR DESCRIPTION
**Pull request by bohai**
Add Installation step for Libcompose Developers
Signed-off-by: Bo Hai <bohai@huawei.com>

### CODE REVIEW

**Comment by bohai** [comment]
Related issue: https://github.com/docker/libcompose/issues/32

**Comment by bohai** [comment]
ping @aanand @aduermael @ibuildthecloud  @gdevillele

**Comment by aanand** [comment]
Not sure I see the point of this versus just running `make binary`. (Though I find it strange that that builds *all* binaries by default.)

**Comment by vdemeester** [comment]
As @aanand said, not sure this is that related with #32 issue : the issue basically says "we can't do go get github.com/docker/libcompose and have something that work as there is dependencies to the non *pkg* packages that depends on the dockerversion generated code".

**Comment by bohai** [comment]
@aanand vdemeester

I think godep is not necessary.
In fact we only need to setup godep path to GOPATH.
Then we can use "go build" command to get the cli binary.

**Comment by vdemeester** [comment]
@bohai true, but https://github.com/docker/libcompose/issues/32#issuecomment-131998164 is all about the fact we currently can't use it because it depends on stuff that depends on `docker/docker/autogen` package.

But you're right, we might even need godep (especially in the Dockerfile).

**Comment by gdevillele** [comment]
so what do we do with this PR?
Do some of you think we should wait for [#32](https://github.com/docker/libcompose/issues/32) to be solved?

**Comment by vdemeester** [comment]
@gdevillele I think it's nice to have something about "How to build libcompose without docker", and this PR would be the answer to that (with little changes). I think #32 will take quite some time to be fixed so we definitly should not wait :wink:.

So either we want something about "How to build libcompose without docker" and we could merge this, either we don't and we should close it. :sweat_smile:

**Comment by dnephin** [comment]
I'm -1 on this. I think if we're going to document a workflow it should be the make+docker workflow, not one that runs on the host.

**Comment by vdemeester** [comment]
@bohai thank you for the PR, but I'm gonna close this one for now. When #32 is *handled* it's not gonna needed anymore, and if we move away from `godep` (which is gonna be likely the case)

Feel free to comment if you think it should be re-open and re-discussed.

**Pull request closed without merging**
