### PR TITLE
add run command

### PR DESCRIPTION
**Pull request by flower-pot**
Mimicking the docker-compose run command in form of

    $ libcompose <service> <command>

Signed-off-by: Frederic Branczyk <fbranczyk@gmail.com>

### CODE REVIEW

**Comment by aanand** [comment]
We should reuse the docker client's code for attaching to containers, rather than re-implementing it - it's a really complex process.

**Comment by flower-pot** [comment]
I agree. Maybe I'll take a look at the docker client once I have some more time on my hand, for now we'll just keep it line by line.

**Comment by flower-pot** [comment]
I think I'm going to try and replace the current wait mechanism with one that closes the whole execution once all goroutines of the log output are closed. From what I found this is done using a WaitGroup.

**Comment by flower-pot** [comment]
So I just pushed a suggestion on how to solve the log synchronisation and showing only the relevant logs. Let me know what you think.

**Comment by flower-pot** [comment]
I revised all my commits and squashed them. Now the only thing I would like to improve is to really attach the container instead of just printing the log output.

**Comment by flower-pot** [comment]
@aanand Do you think it would make sense to essentially instantiate the docker cli and call the [attach command](https://github.com/docker/docker/blob/6733962a2ca66d3d4d58772c378981a9e7da0c15/api/client/attach.go#L19)?

**Comment by aanand** [comment]
@flower-pot Yeah, essentially, though instantiating a CLI object is going to be ugly.

It might be worth trying to extract that code so it's more reusable and submitting it as a PR to docker/docker.

**Comment by flower-pot** [comment]
I agree. I'm going to take a look at how we can do that.

**Comment by ibuildthecloud** [comment]
@flower-pot I agree the CLI functionality should be pulled out.  It would nice if we could find out what the status of https://github.com/docker/docker/issues/15188 is.  Basically there was supposed to be an effort to refactor a lot of the CLI code.

I've been down this path before with other projects I've written and agree that instantiating the docker CLI is a nightmare.  I think the correct first steps would be to figure out how to refactor the code in docker/docker to put the attach logic we need into a reusable pkg.  It's just all the dirty TTY handling that we need.  It can probably be encapsulated pretty well.

**Comment by flower-pot** [comment]
Do you think the core team is going to take care of that? It seems pretty time consuming and I'm probably not the right guy to tackle this as I'm not very familiar with the docker codebase.

**Comment by flower-pot** [comment]
Alright ported to the new dockerclient and now using its attach functionality. What do you think?

**Comment by vdemeester** [comment]
@flower-pot Sorry for the *late* review. Thanks for the PR, few consideration/comments :

- `docker-compose run` supports more flags than this but I think it's good to focus on the main behavior and then the additionnal falgs (I'll create an issue to keep track of diff between `docker-compose` and `libcompose`).
- By default `docker-compose run` start the container with `stdin` and a pseudo-terminal (something like `-ti` in the docker cli). This is not the case in this PR — when I do a `libcompose-cli run myservice /bin/bash`, I can't do anything in it.

I'll take a look at the code too :wink:

**Comment by cpuguy83** [comment]
Here is swarm's hijack implementation: https://github.com/docker/swarm/blob/894d1abd639eedb8234caf63fbc458a6791563bb/api/utils.go#L133

It's a bit cleaner.

**Comment by cpuguy83** [comment]
It's a little different because it's proxying, but probably useful.

**Comment by flower-pot** [comment]
@vdemeester no problem, I haven't had time to revise it either. I think I had the problem that when opening stdin that the stream would never close therefore the execution never ended. But I have to take another look to make sure that's the case.

**Comment by vdemeester** [comment]
@flower-pot still willing (or having time) to work on that ?

**Comment by flower-pot** [comment]
I don't really have the time for it right now. If you don't want to use my changes you can close the PR.

**Comment by vdemeester** [comment]
@flower-pot ok, I'm gonna carry it then :wink:, keeping your commit and iterate on it :+1: 

Thanks for the hard work so far, really appreciated :santa:

**Comment by flower-pot** [comment]
@vdemeester Glad I could help :)

**Comment by vdemeester** [comment]
Carrying in #133.

**Pull request closed without merging**
