### PR TITLE
Split project package into project, config, and yaml packages

### PR DESCRIPTION
**Pull request by joshwget**
Signed-off-by: Josh Curl <hello@joshcurl.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
:+1:

**Comment by joshwget** [comment]
Rebased, although I'm not sure why the build is failing. Any idea @vdemeester?

**Comment by vdemeester** [comment]
`golang.org/x/tools/cmd/vet` is not available anymore it seems (`go vet` is built-in the SDK anyway I think). Submitted #192 to fix it :wink:

**Comment by vdemeester** [comment]
@joshwget you can rebase now, it should be fixe :wink:

**Comment by joshwget** [comment]
@vdemeester It passes now. Thanks!

**Comment by vdemeester** [comment]
LGTM 🐼

**Pull request merged**
