### PR TITLE
Expose Interpolate for external tools

### PR DESCRIPTION
**Pull request by ibuildthecloud**
It is quite useful to parse a text file in the same exact way that
compose does.  One can imagine this being useful for GUI applications or
custom parsers.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I started integrating the variable interpolation into some tools and have found that it is much nicer to be able to be able to interpolate the file the same way that libcompose does internally.

**Comment by vdemeester** [comment]
@ibuildthecloud  Seems ok to me :+1: 

One question though : should or shouldn't it be in a separate package (like `libcompose/interpolate` or something like the `pkg/…` package in docker)

**Comment by ibuildthecloud** [comment]
Hmm.  Yes I could move it to libcompose/interpolate.  I like that.

**Comment by vdemeester** [comment]
@ibuildthecloud still working on it or you would like me to carry it ? :wink:

**Comment by vdemeester** [comment]
Carried by @joshwget in #181

**Pull request closed without merging**
