### PR TITLE
support -v for the rm command

### PR DESCRIPTION
**Pull request by bohai**
Support remove volumes associated with containers.

Signed-off-by: bohai <boh.ricky@gmail.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
@bohai could you squash these two commits ?

**Comment by bohai** [comment]
@vdemeester  OK, i will squash them later.

**Comment by bohai** [comment]
ping @vdemeester 
i have squashed them.

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by vdemeester** [comment]
@bohai needs a rebase
once done, LGTM 🐱

**Comment by vdemeester** [comment]
Thanks a lot @bohai, carrying in #59 (I did the rebase, but this will be your commit :stuck_out_tongue_closed_eyes:). Closing this one but consider it merged (as soon as the build is green)

**Comment by bohai** [comment]
@vdemeester  Thanks.

**Pull request closed without merging**
