### PR TITLE
Linting project package

### PR DESCRIPTION
**Pull request by vdemeester**
Made a `golint` pass on package `project` 🐙.

Main changes :
- `Event` becomes `EventType` and `ProjectEvent` becomes `Event` (because it's in `project` package already).
- The event type names are now CamelCase and prefixed with Event : `SERVICE_ADD -> EventServiceAdd`.
- The same with `State`.

Some improvements, to do probably later (in separate PR and some later on) :
- when docker v1.9 will be released, vendor it and use `StrSlice`instead of `StringorSlice` as it's doing the same thing.
- Refactor a little bit `types_yaml.go` and there is some duplication between `Command` and `StringorSlice` and even more with `MaporEqualSlice`, `MaporColonSlice` and `MaporSpaceSlice`.

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by ibuildthecloud** [comment]
ping @aduermael @gdevillele

**Comment by dnephin** [comment]
LGTM, also needs rebase

@vdemeester what did you use to automate these renames?  Was it just `sed` ?

**Comment by vdemeester** [comment]
@dnephin Good *old* GNU/Emacs, some temporary key binding and a good dose of patience :wink:.

Rebased too :smiley_cat:.

**Comment by dnephin** [comment]
https://github.com/golang/tools/tree/master/refactor looks like an interesting set of tools (there's one for renaming things).  I've never used them, but I hope to get a chance to sometime soon.

**Comment by vdemeester** [comment]
@dnelphin gofmt let u do small refactoring too ;-)

**Pull request merged**
