### PR TITLE
Fix libcompose build cli

### PR DESCRIPTION
**Pull request by vdemeester**
As discovered in #58 a while a go 🐋, the `build` command of the cli (and of the lib) seems to be a little broken :sweat:. 

```bash
root@SZX1000041895:~/build# libcompose build
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose)
INFO[0000] Building build_one...
Successfully built 2a823592c804
INFO[0000] Building build_two...
Step 1 : FROM busybox
 ---> 2c5ac3f849df
Step 2 : CMD echo two
 ---> Using cache
 ---> 1db7a126d491
Successfully built 1db7a126d491
root@SZX1000041895:~/build# libcompose build
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose)
INFO[0000] Building build_one...
Successfully built 2a823592c804
INFO[0000] Building build_two...
Step 1 : FROM busybox
Successfully built 1db7a126d491
root@SZX1000041895:~/build# libcompose build
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose)
INFO[0000] Building build_one...
Step 1 : FROM busybox
 ---> 2c5ac3f849df
Step 2 : CMD echo one
 ---> Using cache
 ---> 2a823592c804
Successfully built 2a823592c804
INFO[0000] Building build_two...
Step 1 : FROM busybox
 ---> 2c5ac3f849df
Step 2 : CMD echo two
 ---> Using cache
 ---> 1db7a126d491
Successfully built 1db7a126d491
```

This PR intend to fix it the simplest way possible :stuck_out_tongue_closed_eyes: 

@imikushin @ibuildthecloud Is there a reason why we are using `Stderr` as output for the build ? (felt strange)

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@vdemeester Seems to me that is should be Stdout, not error.  Tested against `docker-compose` and that uses stdout.  I think it should be switched.

**Comment by imikushin** [comment]
Works fine. Looks good too :)

**Comment by vdemeester** [comment]
@ibuildthecloud it's now using `Stdout` :wink:

**Comment by ibuildthecloud** [comment]
Stupid question, what is this fixing?  What was broken?

**Comment by vdemeester** [comment]
@ibuildthecloud Look at the *code* in the PR message, issuing `libcompose-cli build` wouldn't always print the whole build logs (loosing some lines in the process).

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by vdemeester** [comment]
:tada:

**Pull request merged**
