### PR TITLE
Split integration test

### PR DESCRIPTION
**Pull request by bohai**
https://github.com/docker/libcompose/issues/56
Signed-off-by: Bo Hai <bohai@huawei.com>

### CODE REVIEW

**Comment by bohai** [comment]
ping @ibuildthecloud

**Comment by dnephin** [comment]
LGTM

**Comment by vdemeester** [comment]
@bohai looks good :wink: ! That's probably a nit, but I would rename the `basic_test.go` to `integration_test.go` (or something like that), because it's only where we *setup* the integration now, there is no more tests in it.

**Comment by ibuildthecloud** [comment]
I agree with @vdemeester, once you make those changes should be good to merge.

**Comment by vdemeester** [comment]
ping @bohai

**Comment by bohai** [comment]
@vdemeester Thanks for your advice.
OK, I will do this.

**Comment by bohai** [comment]
ping @vdemeester 
Done, Review again, Thanks.
I will rebase other PRs as soon as this PR merged.

**Comment by vdemeester** [comment]
`common_test.go` looks ok to me too.
LGTM 🐮

**Pull request merged**
