### PR TITLE
Update dependency path for docker/docker/pkg/plugingetter

### PR DESCRIPTION
**Pull request by rheinwein**
`github.com/docker/docker/plugin/getter` now lives at `github.com/docker/docker/pkg/plugingetter`. Updating vendored dependencies to reference the new package name. The outdated package name causes failures in dependency saving/restoration in some cases.

### CODE REVIEW

**Comment by joshwget** [comment]
LGTM. Any idea why we weren't getting an import error using the current path?

**Comment by bfosberry** [comment]
Do you have a cache, or is your local docker/docker out of date?

**Comment by rheinwein** [comment]
Unsure, maybe caching? When we try to save dependencies using Godep in the project that uses libcompose, we get the following error: `godep: Package (github.com/docker/docker/plugin/getter) not found` -- `docker/libcompose` is the only package in our deps that references `getter`.

**Comment by rheinwein** [comment]
Yeah, the whole `docker/docker` could use an update. I just thought plucking out this update would be the least intrusive.

**Comment by rheinwein** [comment]
Oh, it would probably help if I also updated the `github.com/docker/docker/pkg/plugingetter` package in the vendor tree 🙃 I'll fix

**Comment by vdemeester** [comment]
@rheinwein to update the vendor *tree*, you need to update `hack/vendor.sh`, with the commit hash or tag, and run it :angel:.

**Comment by rheinwein** [comment]
@joshwget @vdemeester updated `hack/vendor.sh` with current `docker/docker`. There were a couple new methods added to the engine client in the latest update, so I added them to `NopClient`.

This PR now has:
- an update of `docker/docker`
- changes to `test/nop.go` to implement new methods included in the dep bump
- updating the import path for `docker/docker/pkg/plugingetter`

**Comment by vdemeester** [comment]
@rheinwein thanks :angel: 
One last request :stuck_out_tongue_closed_eyes:, could you squash https://github.com/docker/libcompose/pull/400/commits/46192cee826bffcb5e728fff46454aceaa31e9f6 and https://github.com/docker/libcompose/pull/400/commits/0b2ab048ad3a2de70836bc2127038c87e2a3ff43 :angel:

**Pull request merged**
