### PR TITLE
Update go to 1.6.0.

### PR DESCRIPTION
**Pull request by F21**

### CODE REVIEW

**Comment by vdemeester** [comment]
@F21 Thanks, you beat me to that (I was doing it when receiving the notifications :smile_cat:). Could you sign your commit though ? :angel:

**Comment by F21** [comment]
@vdemeester Done! :smile:

**Comment by vdemeester** [comment]
Thanks !!
LGTM 🐰

**Comment by F21** [comment]
I also updated references to `GO15VENDOREXPERIMENT` because it's now a default in Go 1.6.

**Comment by vdemeester** [comment]
:+1:

**Comment by vdemeester** [comment]
Hum, acceptance tests are getting stuck.. I don't get why :sweat:

**Comment by F21** [comment]
I don't know much about the internals, but were the tests flaky before? Maybe it's just a case of triggering a rebuild.

**Comment by vdemeester** [comment]
@F21 I've retriggered it several times, I'll try to dig into more… :sweat:

**Pull request merged**
